### ISSUE TITLE
Could Lambda OS fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [farlepet/lambda-os#8]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by farlepet** [comment]
The kernel itself is only 639K as it currently stands, and programs do not take up much space either (likely <50K for a a relatively complex program, less if optimized for space), so it could definitely fit on a floppy disk. I just don't have that included as a target currently.

**Comment by informer2016** [comment]
@farlepet Thank you very much for your reply! Nice to hear that it is theoretically possible, that makes your OS much more interesting at least in my point of view ;) Too many bloated OS nowadays, but your OS is not one of them :smiley:

**Comment by farlepet** [comment]
Build target for 1.44MiB floppy images has been added.
